apiVersion: apps/v1
kind: Deployment
metadata:
  name: feature-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feature
  template:
    metadata:
      labels:
        app: feature
    spec:
      containers:
        - name: backend
          image: apurv25/feature-backend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
